-- 1. Retrieve table and column info

-- List all tables in public schema
SELECT tablename FROM pg_tables WHERE schemaname = 'public';

-- List all columns and their data types for a table
SELECT column_name, data_type
FROM information_schema.columns
WHERE table_name = 'Student';

SELECT *
FROM "StudentFees"
WHERE "studentId" = '17159'
  AND "academicYear" = 'Y2024_2025';


-- 3. 1. Generate reset statements for all sequences

-- This generates ALTER SEQUENCE statements for all serial/bigserial columns
SELECT 
  'ALTER SEQUENCE "' || sequence_name || '" RESTART WITH ' || 
  COALESCE(
    '(SELECT COALESCE(MAX(' || column_name || '),0) + 1 FROM "' || table_name || '")', 
    1
  ) || ';' AS reset_command
FROM information_schema.sequences s
JOIN information_schema.columns c 
  ON s.sequence_name = c.column_default::text LIKE '%' || s.sequence_name || '%';

  SELECT 
  'ALTER SEQUENCE "' || s.sequence_name || '" RESTART WITH ' ||
  (SELECT COALESCE(MAX(id), 0) + 1 FROM "Subject") || ';' AS reset_command
FROM information_schema.sequences s
WHERE s.sequence_name LIKE '%Subject%id%seq%';

SELECT 
  'ALTER SEQUENCE "' || s.sequence_name || '" RESTART WITH ' ||
  (SELECT COALESCE(MAX(id), 0) + 1 FROM "class") || ';' AS reset_command
FROM information_schema.sequences s
WHERE s.sequence_name LIKE '%Class%id%seq%';

ALTER SEQUENCE "class_id_seq" RESTART WITH 1;



-- 2. Basic SELECT queries

-- Retrieve all records
SELECT * FROM "Admin";
SELECT * FROM "Student";
SELECT * FROM "Teacher" WHERE "status" = 'TRANSFERRED';
SELECT * FROM "Teacher";
SELECT * FROM "class";
SELECT * FROM "Grade";
SELECT * FROM "Branch";
SELECT * FROM "FeeStructure";
SELECT * FROM "FeesCollection";
SELECT * FROM "StudentFees";
SELECT * FROM "StudentTotalFees";
SELECT * FROM "FeeTransaction";
SELECT * FROM "Exam";
SELECT * FROM "ExamSubject";
SELECT * FROM "Subject";
SELECT * FROM "Homework";
SELECT * FROM "Lesson";
SELECT * FROM "Result";
SELECT * FROM "Attendance";
SELECT * FROM "Messages";
SELECT * FROM "AcademicYear";
SELECT * FROM "Profile" WHERE clerk_id is not null;
SELECT * FROM "LinkedUser";
SELECT * FROM "StudentEnrollment";
UPDATE "Student"
SET "admissionNo" = "id";

ALTER TABLE "FeeStructure"
ALTER COLUMN id
ADD GENERATED BY DEFAULT AS IDENTITY;

-- 1️⃣ Drop the old default (broken serial or static)
ALTER TABLE "FeeStructure" ALTER COLUMN id DROP DEFAULT;

-- 2️⃣ Attach a proper sequence generator
CREATE SEQUENCE IF NOT EXISTS feestructure_id_seq OWNED BY "FeeStructure".id;

-- 3️⃣ Use that sequence as the default value
ALTER TABLE "FeeStructure" ALTER COLUMN id SET DEFAULT nextval('feestructure_id_seq');

SELECT setval(pg_get_serial_sequence('"FeeStructure"', 'id'),
              COALESCE((SELECT MAX(id) FROM "FeeStructure"), 0) + 1,
              false);

INSERT INTO "FeeStructure" ("gradeId", "startDate", "dueDate", "termFees", "term", "academicYear")
VALUES (5, NOW(), NOW(), 8000, 'TERM_1', 'Y2025_2026')
RETURNING id;





-- 3. Filtered SELECTs / joins
-- Students in a specific class
SELECT s.*
FROM "Student" s
JOIN "Class" c ON s."classId" = c.id
WHERE c.grade_id = 2;

-- Teachers supervising a class
SELECT t."name", c."name"
FROM "Teacher" t
LEFT JOIN "Class" c ON t.id = c."supervisorId";

-- Student fees details
SELECT sf.*
FROM "StudentFees" sf
JOIN "Student" s ON sf."studentId" = s.id
WHERE s.id = '17159';

-- Attendance of a specific student
SELECT * 
FROM "Attendance"
WHERE "studentId" = '13738';

-- Homework in a date range
SELECT id, date 
FROM "Homework"
WHERE date BETWEEN '2025-03-18' AND '2025-03-20';

-- Truncate all tables & restart IDs
DO
$$
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = 'public') LOOP
        EXECUTE 'TRUNCATE TABLE "' || r.tablename || '" RESTART IDENTITY CASCADE;';
    END LOOP;
END
$$;

TRUNCATE TABLE
  "Admin",
  "Grade",
  "class",
  "Teacher",
  "Lesson",
  "Subject",
  "Announcement",
  "Messages",
  "Student",
  "Event",
  "Exam",
  "ExamGradeSubject",
  "Homework",
  "Result",
  "ClerkStudents",
  "ClerkTeachers",
  "SubjectTeacher",
  "FeeStructure",
  "StudentFees",
  "FeeTransaction",
  "StudentTotalFees",
  "Attendance",
  "CancelledReceipt",
  "PermissionSlip",
  "_SubjectGrades"
RESTART IDENTITY CASCADE;

SELECT *
FROM "Student"
LIMIT 10;

SELECT id, clerk_id, length(clerk_id), encode(clerk_id::bytea, 'escape')
FROM "Student"
WHERE id = 15616;

SELECT * FROM "Attendance"  ;
SELECT *
FROM "Attendance"
WHERE "date" >= '2025-12-21 00:00:00'
  AND "date" <  '2025-12-22 00:00:00';

SELECT *
FROM "Attendance"
WHERE "date" >= '2025-01-02 00:00:00' AND "date" <  '2025-01-03 23:59:59';

DELETE FROM "Attendance" WHERE "date" >= '2025-01-02 00:00:00' AND "date" <  '2025-01-03 23:59:59';

DELETE FROM "class";

DROP TABLE "Attendance";

SELECT migration_name, finished_at
FROM _prisma_migrations
ORDER BY finished_at;

SELECT * FROM "Student" WHERE "classId" = 43;
SELECT * FROM "SchoolInfo";
SELECT * FROM "Exam";
SELECT * FROM "ExamGradeSubject";
SELECT * FROM "Result";
SELECT * FROM "Subject";
SELECT * FROM "Profile";
SELECT * FROM "LinkedUser";

INSERT INTO "SchoolInfo" (
  "id","name","address","phone","email","website","logo",
  "taxId","receiptHeader","receiptFooter","createdAt","updatedAt","schoolId"
) VALUES (
  'cmkz9t8ab000304l5xyz987pq',
  'ST. MARY''S ENGLISH MEDIUM SCHOOL',
  '12-45-7, Seethammadhara, Visakhapatnam',
  '9876543210',
  'stmarysvizag@gmail.com',
  'https://stmarysvizag.edu.in/',
  NULL,
  'AP112',
  '(Recognized by Government of Andhra Pradesh) Affiliation No. AP/112 - Dt. 15-08-1995',
  'All fees are subject to school policies.',
  NOW(),
  NOW(),
  'smes_vizag'
);

-- 1️⃣ SchoolInfo
INSERT INTO "SchoolInfo" (
  "id","name","address","phone","email","website","logo",
  "taxId","receiptHeader","receiptFooter","createdAt","updatedAt","schoolId"
) VALUES (
  'testing_school',
  'KOTAK SALESIAN SCHOOL',
  '17-309, Golla Veedhi, Old Gopalapatnam',
  '9949523412',
  'kotakschoolvsp@gmail.com',
  'https://kotaksalesianschool-vizag.com/',
  NULL,
  'AP050',
  '(Affiliated to the Council for the I.S.C. Examination, New Delhi) Affiliation No. AP/050 - Dt. 04-11-1987',
  'Fees once paid are not refundable.',
  NOW(),
  NOW(),
  'test'
);

SELECT * FROM "SchoolInfo";


-- 2️⃣ Profile
INSERT INTO "Profile" (
  "id","clerk_id","phone","activeUserId"
) VALUES (
  'cmjf4q3hm00006cjq2nnukul3',
  'user_34hDQUMuHoPtvaWMWsrnYaAYztu',
  '7801049830',
  NULL
);

SELECT * FROM "Profile";



-- 3️⃣ LinkedUser (ONLY ONCE)
INSERT INTO "LinkedUser" (
  "id","username","role","profileId","schoolId"
) VALUES (
  'cmjf4q3hv00016cjqg8jf9op8',
  'admin001',
  'admin',
  'cmjf4q3hm00006cjq2nnukul3',
  'testing_school'
);

SELECT * FROM "LinkedUser";

-- 4️⃣ Update Profile activeUserId
UPDATE "Profile"
SET "activeUserId" = 'cmjf4q3hv00016cjqg8jf9op8'
WHERE "id" = 'cmjf4q3hm00006cjq2nnukul3';


-- 5️⃣ Admin
INSERT INTO "Admin" (
  "id","username","password","name","parentName","gender","email",
  "phone","address","dob","img","bloodType","createdAt",
  "clerk_id","profileId","linkedUserId","schoolId"
) VALUES (
  'cmjf4q3i600026cjqnm2xzto4',
  'admin001',
  'tester0001',  -- 🔐 use bcrypt
  'A HARIKIRAN',
  'A SRINIVASARAO',
  'Male',
  'hari.myskoolcom@gmail.com',
  '7801049830',
  '17-309, Golla Veedhi, Old Gopalapatnam',
  '1996-03-29',
  'https://res.cloudinary.com/harikiran/image/upload/v1766285381/h4x8fjbq7hlfkvbv4vg9.jpg',
  'O_POS',
  NOW(),
  'user_34hDQUMuHoPtvaWMWsrnYaAYztu',
  'cmjf4q3hm00006cjq2nnukul3',
  'cmjf4q3hv00016cjqg8jf9op8',
  'testing_school'
);

INSERT INTO "Branch" (id, name, type, "order", "schoolId") VALUES
(1, 'Kinder Garten', 'KINDERGARTEN', 1, 'testing_school'),
(2, 'Primary', 'PRIMARY', 2, 'testing_school'),
(3, 'Secondary', 'HIGHER', 3, 'testing_school');

SELECT id,  role FROM "LinkedUser";

SHOW max_connections;

SELECT count(*) FROM pg_stat_activity;

SELECT pid, state, query
FROM pg_stat_activity
WHERE datname = 'multi_schooldb';

SELECT * FROM "SchoolInfo";